#!/bin/bash
set -eu

DB_HOST_USER="${DB_HOST_USER:-cpanelhost}"
DB_HOST_PASSWORD="${DB_HOST_PASSWORD:-change_me_host_password}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE USER IF NOT EXISTS '${DB_HOST_USER}'@'%' IDENTIFIED BY '${DB_HOST_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${DB_HOST_USER}'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOSQL
